import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "a42z - World's 1st Agentic Hackathon Judge",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.ico", type: "image/x-icon" }
    ]
  },
  other: {
    "format-detection": "telephone=no, date=no, email=no, address=no"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <head>
        <title>a42z Judge</title>
      </head>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
